first=str(input("Please enter a sentence: "))
replace=input("Please enter a word you want to replace: ")
output=input("Please enter the word you want replace it with: ")
modified_str=first.replace(replace,output)
print("The modified string is : ",modified_str)
