first_name=input("What's your first name?: ")
last_name=input("Wats your last name?: ")
print("Your full name is:", first_name, last_name)
colour=input("Ok " + first_name + " what's your favourite colour?: ")
print("Your favourite colour is", colour)
age=int(input("How old are you?: "))
print("OK! Your name is", first_name, last_name, "you are", age, "and your favourite colour is", colour)
